package com.triple7.healthshield254.navigation

const val ROUT_HOME = "home"
const val ROUT_SPLASH = "splash"
const val ROUT_SCANVERIFY = "ScanVerifyScreen"
const val ROUT_REPORTMEDICINE= "ReportMedicineScreen"
const val ROUT_CROWDSOURCING= "CrowdsourcingHubScreen"
const val ROUT_EDUCATIONALHUB= "EducationalHubScreen"
const val ROUT_HOTSPOTMAP= "HotspotMapScreen"
const val ROUT_PROFILESETTINS= "ProfileSettingsScreen"
const val ROUT_VERIFICATIONRECORDS= "ScanHistoryScreen"
const val ROUT_REGISTER= "RegistrationScreen"
const val ROUT_LOGIN= "LoginScreen"
const val ROUT_SENDREPORT= "ReportScreen"
const val ROUT_VIEWREPORT= "viewreport"
const val ROUT_ONBOARDING1= "Onboarding1"
const val ROUT_ONBOARDING2= "Onboarding2"
const val ROUT_MEDICINE= "medicine"
const val ROUT_PLACEORDER= "PlaceOrderScreen"
const val ROUT_SUPPLIERMANUFACTURER= "SupplierManufacturerDashboard"
const val ROUT_ADMIN= "admin"
const val ROUT_UPLOADMEDICINE= "uploadmedicine"
const val ROUT_LAUNCHSCREEN= "ChatBoardScreen"
const val ROUT_CHATBOARDCHSCREEN= "LaunchScreen"
//const val ROUT_SCANMEDICINE= "ScanMedicine"
