package com.triple7.healthshield254.navigation

const val ROUT_HOME = "home"
const val ROUT_SPLASH = "splash"
const val ROUT_SCANVERIFY = "ScanVerifyScreen"
const val ROUT_REPORTMEDICINE= "ReportMedicineScreen"
const val ROUT_CROWDSOURCING= "CrowdsourcingHubScreen"
const val ROUT_EDUCATIONALHUB= "EducationalHubScreen"
const val ROUT_HOTSPOTMAP= "HotspotMapScreen"
const val ROUT_PROFILESETTINS= "ProfileSettingsScreen"
const val ROUT_VERIFICATIONRECORDS= "ScanHistoryScreen"
const val ROUT_REGISTER= "RegisterScreen"
const val ROUT_LOGIN= "LoginScreen"
const val ROUT_SENDREPORT= "sendreport"
const val ROUT_VIEWREPORT= "viewreport"
